### ISSUE TITLE
Soft 404 errors: /404 and /404.html incorrectly return HTTP 200 OK

### ISSUE THREAD

**Issue by SmashManiac** [video-game-randomizers/rando-list#16]
Requesting `/404` or `/404.html` returns HTTP 200 OK in the response headers, even though the response body claims that it's a 404 error page. Those pages are therefore soft 404 errors.

Soft 404 errors can cause issues with web crawling bots and search engines, and should be fixed to return HTTP 404 Not Found if possible. If a direct fix is not possible, it may be worth looking into redirects as a potential workaround.

More information about soft 404 errors:
https://developers.google.com/search/docs/crawling-indexing/http-network-errors?hl=en#soft-404-errors

**Comment by ManicJamie** [comment]
To my knowledge this is expected behaviour; requesting /404 correctly finds the 404 page and returns it successfully.

This is a consequence of how GH-pages allows custom 404 pages - they must be stored with permalink `404.html`, so they will always be accessible legitimately at `/404`

I don't think this is an issue here; User-agents should not ever request /404 and expect anything other than a 404 page, and crawlers are not going to get directed to /404. One might even argue that the semantics here are correct; the server is returning exactly what you requested.

As-is, requesting a truly nonexistent page (eg. /test) correctly raises a 404.

**Comment by SmashManiac** [comment]
That may be true, but the fact remains that we're having the HTTP headers contradict the HTTP body in this case, which should definitely not happen.

Regardless, I believe it's worth fixing if we can, if only to avoid the potential SEO penalty, since Google Search Console generally flags this as an error.

Worst case scenario, adding a robots.txt file could also be a possible workaround to prevent this SEO issue.

**Comment by duncathan** [comment]
> That may be true, but the fact remains that we're having the HTTP headers contradict the HTTP body in this case, which should definitely not happen.

there's no contradiction. as far as I know, this is a standard practice for a custom 404 page. the requested content is being delivered as expected, so it's status 200.

the appropriate way to handle this for SEO is to exclude the 404 page from your sitemap (do we have a sitemap?) and optionally to include a `noindex` meta tag on your 404 page. of course, there shouldn't be anything linking directly to the 404 page anyway, so it's unlikely the crawler would even discover the page in first place

**Comment by duncathan** [comment]
btw: 
> if only to avoid the potential SEO penalty

there is no "penalty" applied for soft 404s. all it means is that the page will not be indexed, which is precisely the behaviour we want for our 404 page anyway. it's just good practice to do so explicitly rather than rely on the search engine to be smart enough to figure out on its own that the page shouldn't be indexed.
